"""Iterative policy updates used at inference time.

Mainline inference uses a semantic-Fisher sphere retraction driven by a predicted
log-rate. Closed-form exponential potential updates remain available as ablations.
"""
from __future__ import annotations

import torch

from ..flow.natural_path import natural_endpoint_from_potential, solve_beta_for_target_kl
from ..flow.semantic_fisher import semantic_fisher_sphere_step


def closed_form_policy_update(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    beta: torch.Tensor | float = 1.0,
    eps: float = 1e-12,
) -> torch.Tensor:
    """Closed-form natural-flow policy update generated by a potential."""
    return natural_endpoint_from_potential(p_start, potential, beta=beta, eps=eps)


def semantic_fisher_policy_update(
    p_start: torch.Tensor,
    lograte: torch.Tensor,
    step_dt: float = 1.0,
    eps: float = 1e-12,
) -> torch.Tensor:
    """One semantic-Fisher sphere-retraction update generated by a log-rate."""
    return semantic_fisher_sphere_step(p_start, lograte, dt=step_dt, eps=eps)


def beta_for_update(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    mode: str = "fixed_beta",
    beta: float = 1.0,
    target_kl: float = 0.05,
    beta_max: float = 10.0,
    bisection_steps: int = 20,
):
    if mode == "fixed_beta":
        return float(beta)
    if mode == "target_kl":
        return solve_beta_for_target_kl(
            p_start,
            potential,
            target_kl=target_kl,
            beta_max=beta_max,
            bisection_steps=bisection_steps,
        )
    raise ValueError(f"unknown update mode: {mode}")


def simplex_flow_update(p_start: torch.Tensor, velocities: list[torch.Tensor],
                        step_size: float = 1.0, eps: float = 1e-12) -> torch.Tensor:
    p = p_start.clamp(min=eps)
    p = p / p.sum(dim=-1, keepdim=True).clamp(min=eps)
    dt = float(step_size) / max(len(velocities), 1)
    for v in velocities:
        vv = v.to(device=p.device, dtype=p.dtype)
        vv = vv - vv.mean(dim=-1, keepdim=True)
        p = (p + dt * vv).clamp(min=eps)
        p = p / p.sum(dim=-1, keepdim=True).clamp(min=eps)
    return p
