"""Exponential Fisher natural-gradient path on a local action simplex.

Main path:
    p_lambda(a) ∝ p_start(a) exp(lambda * beta * potential(a))
    dp/dlambda = beta * p_lambda(a) * (potential(a) - E_{p_lambda}[potential])

Square-root Fisher-sphere path:
    z_lambda(a) ∝ exp(lambda * beta * potential(a) / 2) * sqrt(p_start(a))

This plain Fisher path is retained for the closed-form potential ablation. The
semantic-Fisher pullback mainline lives in ``flow/semantic_fisher.py``.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import torch

from ..utils.numerical import EPS, normalize_simplex


@dataclass
class NaturalFlowSample:
    p_start: torch.Tensor
    p_lambda: torch.Tensor
    dp_dlambda: torch.Tensor
    p_target: torch.Tensor
    lambda_value: torch.Tensor
    advantages: torch.Tensor
    scores: torch.Tensor | None = None
    z_lambda: torch.Tensor | None = None
    dz_dlambda: torch.Tensor | None = None
    condition_metadata: dict = field(default_factory=dict)


def smooth_simplex(p: torch.Tensor, eps: float = EPS, dim: int = -1) -> torch.Tensor:
    """Make a support distribution strictly positive and normalized."""
    p = torch.nan_to_num(p, nan=0.0, posinf=0.0, neginf=0.0).clamp(min=eps)
    return normalize_simplex(p, dim=dim, eps=eps)


def effective_advantage_from_target(
    p_start: torch.Tensor,
    p_target: torch.Tensor,
    beta: float | None = None,
    eps: float = EPS,
    center: bool = True,
    eta: float | None = None,
) -> torch.Tensor:
    """Return A_eff whose exponential path maps p_start to p_target at lambda=1.

    ``eta`` is accepted as a legacy alias for ``beta``.
    Any additive constant is immaterial to the path velocity. When ``center`` is true,
    the returned advantage has zero expectation under ``p_start`` for stable logs.
    """
    beta = _resolve_beta(beta, eta)
    if beta <= 0:
        raise ValueError("beta must be positive")
    p_start = smooth_simplex(p_start, eps=eps)
    p_target = smooth_simplex(p_target, eps=eps)
    adv = (p_target.clamp_min(eps).log() - p_start.clamp_min(eps).log()) / float(beta)
    if center:
        adv = adv - (p_start * adv).sum(dim=-1, keepdim=True)
    return torch.nan_to_num(adv, nan=0.0, posinf=0.0, neginf=0.0)


def apply_proposal_correction(
    advantages: torch.Tensor,
    proposal_prob: torch.Tensor,
    beta: float | None = None,
    eps: float = EPS,
    eta: float | None = None,
) -> torch.Tensor:
    """Convert sampled-support advantages into proposal-corrected advantages."""
    beta = _resolve_beta(beta, eta)
    if beta <= 0:
        raise ValueError("beta must be positive")
    proposal = proposal_prob.to(device=advantages.device, dtype=advantages.dtype).clamp_min(eps)
    return advantages - proposal.log() / float(beta)


def natural_endpoint_from_potential(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    beta: torch.Tensor | float,
    eps: float = EPS,
) -> torch.Tensor:
    """Closed-form endpoint generated by a support-local potential.

    ``potential`` may be a true advantage or a model-predicted score. Additive
    constants in the potential cancel in the softmax.
    """
    p_start = smooth_simplex(p_start, eps=eps)
    potential = torch.nan_to_num(potential.to(device=p_start.device, dtype=p_start.dtype))
    beta_t = _beta_for_action_axis(torch.as_tensor(beta, device=p_start.device, dtype=p_start.dtype), p_start)
    logits = p_start.clamp_min(eps).log() + beta_t * potential
    return torch.softmax(logits, dim=-1)


def natural_path_from_potential(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    beta: torch.Tensor | float,
    lambda_value: torch.Tensor | float,
    eps: float = EPS,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Return ``(p_lambda, dp_dlambda)`` for the exponential natural-flow family."""
    p_start = smooth_simplex(p_start, eps=eps)
    potential = torch.nan_to_num(potential.to(device=p_start.device, dtype=p_start.dtype))
    beta_t = _beta_for_action_axis(torch.as_tensor(beta, device=p_start.device, dtype=p_start.dtype), p_start)
    lam = _lambda_for_action_axis(torch.as_tensor(lambda_value, device=p_start.device, dtype=p_start.dtype), p_start)
    p_lambda = torch.softmax(p_start.clamp_min(eps).log() + lam * beta_t * potential, dim=-1)
    mean_potential = (p_lambda * potential).sum(dim=-1, keepdim=True)
    dp = beta_t * p_lambda * (potential - mean_potential)
    dp = dp - dp.sum(dim=-1, keepdim=True) / p_start.shape[-1]
    return p_lambda, dp


def sphere_path_from_potential(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    beta: torch.Tensor | float,
    lambda_value: torch.Tensor | float,
    eps: float = EPS,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Return ``(z_lambda, dz_dlambda)`` on the positive Fisher sphere.

    ``z_lambda`` is the square-root sphere coordinate whose elementwise square equals
    the probability path generated by ``natural_path_from_potential``.
    """
    p_start = smooth_simplex(p_start, eps=eps)
    potential = torch.nan_to_num(potential.to(device=p_start.device, dtype=p_start.dtype))
    beta_t = _beta_for_action_axis(torch.as_tensor(beta, device=p_start.device, dtype=p_start.dtype), p_start)
    lam = _lambda_for_action_axis(torch.as_tensor(lambda_value, device=p_start.device, dtype=p_start.dtype), p_start)
    z0 = p_start.clamp_min(eps).sqrt()
    weights = torch.exp(0.5 * lam * beta_t * potential)
    unnormalized = weights * z0
    z_lambda = unnormalized / unnormalized.norm(dim=-1, keepdim=True).clamp_min(eps)
    mean_potential = (z_lambda.square() * potential).sum(dim=-1, keepdim=True)
    dz = 0.5 * beta_t * z_lambda * (potential - mean_potential)
    dz = dz - (dz * z_lambda).sum(dim=-1, keepdim=True) * z_lambda
    return z_lambda, dz


def kl_to_start_for_beta(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    beta: torch.Tensor | float,
    eps: float = EPS,
) -> torch.Tensor:
    """Compute KL(p_beta || p_start) for a potential-generated endpoint."""
    p_start = smooth_simplex(p_start, eps=eps)
    p_beta = natural_endpoint_from_potential(p_start, potential, beta=beta, eps=eps)
    return (p_beta * (p_beta.clamp_min(eps).log() - p_start.clamp_min(eps).log())).sum(dim=-1)


def solve_beta_for_target_kl(
    p_start: torch.Tensor,
    potential: torch.Tensor,
    target_kl: float,
    beta_max: float = 10.0,
    bisection_steps: int = 20,
    eps: float = EPS,
) -> float | torch.Tensor:
    """Solve the update strength beta for a KL budget by bisection.

    For a scalar support this returns a Python float. For a batch it returns one beta
    per batch row. If the potential is constant on a support, beta is zero.
    """
    if target_kl <= 0.0 or beta_max <= 0.0:
        return 0.0
    p_start = smooth_simplex(p_start, eps=eps)
    potential = torch.nan_to_num(potential.to(device=p_start.device, dtype=p_start.dtype))
    centered = potential - (p_start * potential).sum(dim=-1, keepdim=True)
    has_signal = centered.abs().amax(dim=-1) > 1e-10
    if not bool(has_signal.any().detach().cpu()):
        return 0.0

    shape = p_start.shape[:-1]
    lo = torch.zeros(shape, device=p_start.device, dtype=p_start.dtype)
    hi = torch.full(shape, float(beta_max), device=p_start.device, dtype=p_start.dtype)
    target = torch.full(shape, float(target_kl), device=p_start.device, dtype=p_start.dtype)
    hi_kl = kl_to_start_for_beta(p_start, potential, hi, eps=eps)
    saturated = hi_kl < target
    for _ in range(int(bisection_steps)):
        mid = 0.5 * (lo + hi)
        mid_kl = kl_to_start_for_beta(p_start, potential, mid, eps=eps)
        go_hi = mid_kl < target
        lo = torch.where(go_hi, mid, lo)
        hi = torch.where(go_hi, hi, mid)
    beta = torch.where(saturated, torch.full_like(hi, float(beta_max)), hi)
    beta = torch.where(has_signal, beta, torch.zeros_like(beta))
    if beta.dim() == 0:
        return float(beta.detach().cpu())
    return beta


class ExponentialNaturalFlowPath:
    """Closed-form natural flow induced by support-local advantages."""

    def sample(
        self,
        p_start: torch.Tensor,
        advantages: torch.Tensor,
        lambda_value: torch.Tensor | float,
        beta: float | None = None,
        eps: float = EPS,
        scores: torch.Tensor | None = None,
        condition_metadata: dict | None = None,
        eta: float | None = None,
    ) -> NaturalFlowSample:
        beta = _resolve_beta(beta, eta)
        if beta <= 0:
            raise ValueError("beta must be positive")
        if not torch.isfinite(advantages).all():
            raise ValueError("advantages must be finite")
        lam = torch.as_tensor(lambda_value, dtype=p_start.dtype, device=p_start.device)
        p_start = smooth_simplex(p_start, eps=eps)
        advantages = torch.nan_to_num(advantages.to(device=p_start.device, dtype=p_start.dtype))
        p_lambda, dp = natural_path_from_potential(p_start, advantages, beta=beta, lambda_value=lam, eps=eps)
        p_target = natural_endpoint_from_potential(p_start, advantages, beta=beta, eps=eps)
        z_lambda, dz = sphere_path_from_potential(p_start, advantages, beta=beta, lambda_value=lam, eps=eps)

        return NaturalFlowSample(
            p_start=p_start,
            p_lambda=p_lambda,
            dp_dlambda=dp,
            p_target=p_target,
            lambda_value=lam,
            advantages=advantages,
            scores=scores,
            z_lambda=z_lambda,
            dz_dlambda=dz,
            condition_metadata=condition_metadata or {},
        )


def _lambda_for_action_axis(lambda_value: torch.Tensor, p: torch.Tensor) -> torch.Tensor:
    if lambda_value.dim() == 0:
        return lambda_value
    lam = lambda_value.to(device=p.device, dtype=p.dtype)
    while lam.dim() < p.dim():
        lam = lam.unsqueeze(-1)
    return lam


def _beta_for_action_axis(beta: torch.Tensor, p: torch.Tensor) -> torch.Tensor:
    bb = beta.to(device=p.device, dtype=p.dtype)
    while bb.dim() < p.dim():
        bb = bb.unsqueeze(-1)
    return bb


def _resolve_beta(beta: float | None, eta: float | None) -> float:
    if beta is None:
        if eta is None:
            raise TypeError("beta is required")
        beta = eta
    elif eta is not None and float(eta) != float(beta):
        raise ValueError("beta and legacy eta alias disagree")
    return float(beta)
